# Generated by Django 3.2.9 on 2021-11-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LeadQuality', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('submodel', models.CharField(max_length=100)),
                ('owned_or_leased', models.CharField(max_length=30)),
                ('distance', models.IntegerField()),
                ('annual_distance', models.IntegerField()),
                ('deductible', models.IntegerField()),
                ('deductible2', models.IntegerField()),
                ('Preferred_Level_Of_Coverage', models.CharField(max_length=30)),
                ('has_coverage', models.CharField(max_length=20)),
                ('former_insurer', models.CharField(max_length=30)),
                ('months_insured', models.IntegerField()),
                ('Relationship', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('birthdate', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('marital_status', models.CharField(max_length=10)),
                ('Military_experience', models.CharField(max_length=10)),
                ('occupation', models.CharField(max_length=30)),
                ('driver_state', models.CharField(max_length=30)),
                ('license_status', models.CharField(max_length=10)),
                ('sr22', models.CharField(max_length=10)),
                ('incidentpop', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=20)),
                ('own_or_rent', models.CharField(max_length=10)),
                ('credit_rating', models.CharField(max_length=30)),
                ('primary_phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=50)),
                ('years_at_address', models.IntegerField()),
                ('secondary_phone', models.CharField(max_length=50)),
                ('contact_method', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('occupation_years', models.IntegerField()),
                ('highest_level', models.CharField(max_length=30)),
                ('revoked', models.CharField(max_length=10)),
                ('repossessions', models.CharField(max_length=10)),
                ('licensed_age', models.IntegerField()),
                ('bankruptcy', models.CharField(max_length=5)),
                ('at_home_student', models.CharField(max_length=5)),
                ('IsGoodStudent', models.CharField(max_length=5)),
                ('days_used', models.IntegerField()),
                ('use', models.CharField(max_length=20)),
                ('location_parked', models.CharField(max_length=20)),
                ('antitheft', models.CharField(max_length=20)),
                ('VinInPolk', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('bodilyinjury_person', models.IntegerField()),
                ('bodilyinjury_accident', models.IntegerField()),
                ('propertydamage', models.CharField(max_length=30)),
            ],
        ),
    ]
